import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>AlwaysAI TakeHome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        body
      </main>
    </div>
    </Layout>
  )
}
